### ISSUE TITLE
Calendar Widget

### ISSUE THREAD

**Issue by gonzoinc** [jameswlane/status-board#104]
Do you have or know of a replacement for the default/Demo Calendar widget? The current one uses iCal which looks to be abandoned and does not work with reoccurring events which looks to be due to dependancies being outdated and the widget itself is just bad in general. I've been searching but have not come up with anything yet.

Thanks again.

**Comment by jameswlane** [comment]
Doing a quick search I would think we would replace it with something like [node-google-calendar](https://www.npmjs.com/package/node-google-calendar). The developer of [ical](https://github.com/peterbraden/ical.js) has only made one release and hasn't made another I wouldn't consider it actively developed. This is something I can dig into later, if you want to give it a try and PR the code back to the [cli](https://github.com/jameswlane/status-board-example) where the generator code will live or the [example](https://github.com/jameswlane/status-board-example) project, then I could move the code over to the generator.

**Comment by gonzoinc** [comment]
I'm not specifically using a Google Calendar. I'm pulling in the ICS for a Confluence calendar so it just needs to be able to work with an external URL referenced ics file. 

I looked at [ical-expander)](https://github.com/mifi/ical-expander) but it looks to only handle local files from what I see on their limited documentation. I tried using [request](https://github.com/request/request) to pull the data into memory which worked, but icalExpander errors calling parser._eachLine in iCal.js trying to read the buffer.length.  

Below is what I have using icalexpander: job called newcalendar.js

`var ical = require('ical');
var IcalExpander = require("ical-expander");
var request = require('request');


module.exports = {

  onInit: function(config, dependencies) {
    dependencies.logger.info('calendar job started!'); // I am a log line!
  },

    onRun: function (config, dependencies, jobCallback) {
        
        request.get({url:config.calendarUrl,json:false}, function (error, response, body) {
            
            if (error) {
                dependencies.logger.info(error);

              }
              
            if (!error && response.statusCode == 200) {
                var data = body;
                dependencies.logger.info(data);
                
                const icalExpander = new IcalExpander(data);
            }
        });
    }    
};`

Dump from the request to logger:

`BEGIN:VCALENDAR
PRODID:-//Atlassian Confluence//Calendar Plugin 1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:Engineering Calendar
X-WR-CALDESC:General Engineering to list all events and such. Not to be u
 sed for PTO.
X-WR-TIMEZONE:America/New_York
X-MIGRATED-FOR-USER-KEY:true
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:America/New_York
TZURL:http://tzurl.org/zoneinfo/America/New_York
SEQUENCE:61641
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-045602
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:18831118T120358
RDATE:18831118T120358
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19180331T020000
RDATE:19180331T020000
RDATE:19190330T020000
RDATE:19200328T020000
RDATE:19210424T020000
RDATE:19220430T020000
RDATE:19230429T020000
RDATE:19240427T020000`


Error it keeps getting stuck on.

`/usr/local/board/node_modules/ical.js/build/ical.js:2098
    var len = buffer.length;
                    ^

TypeError: Cannot read property 'length' of undefined
    at Function.ICAL.parse.parser._eachLine (/usr/local/board/node_modules/ical.js/build/ical.js:2098:21)
    at Object.parser [as parse] (/usr/local/board/node_modules/ical.js/build/ical.js:1670:12)
    at new IcalExpander (/usr/local/board/node_modules/ical-expander/index.js:15:26)
    at Request._callback (/usr/local/board/packages/demo/jobs/newcalendar/newcalendar.js:25:38)
    at Request.self.callback (/usr/local/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! your-dashboard-name-here@0.0.1 start: `node start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-dashboard-name-here@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Not sure if this helps at all.  Biggest issue I need to work around is the reoccuring events.
