### ISSUE TITLE
Status Board won't start due to error in Logger

### ISSUE THREAD

**Issue by jameswlane** [jameswlane/status-board#57]
What you did:
Ran `yarn start`

What happened:
```
/Users/jameswlane/Projects/GitHub/jameswlane/status-board-example/node_modules/status-board/lib/logger.js:5
const config = config_manager_1.default('logging');
                                       ^

TypeError: config_manager_1.default is not a function
    at Object.<anonymous> (/Users/jameswlane/Projects/GitHub/jameswlane/status-board-example/node_modules/status-board/lib/logger.js:5:40)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jameswlane/Projects/GitHub/jameswlane/status-board-example/node_modules/status-board/lib/config-manager.js:7:18)
    at Module._compile (module.js:643:30)
```

**Comment by jameswlane** [comment]
Closing issue
Fixed in this [commit](f9bedc632ba5b7ac2906961a871822eef690425f)
