### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by dtsuran** [jameswlane/status-board#577]
> status-board@0.0.0-development start /mnt/ssdstore/dev/status-boards/status-board
> node ./bin/www

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/mnt/ssdstore/dev/status-boards/status-board/bin/www'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! status-board@0.0.0-development start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the status-board@0.0.0-development start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jameswlane** [comment]
@dtsuran Could I get a little more info on this error?

- What version `status-board` are you using?
- What version of Node.js?:
- What does the entry point for your dashboard application look like?
- What you do to get this error?
- Could you provide me a reproduction repository?

If possible, please create a repository that reproduces the issue with the
minimal amount of code possible.

**Comment by dtsuran** [comment]
1. I use current version of `status-board`.
2. Node.js v10.15.1

Step to reproduce:
1. `git clone https://github.com/jameswlane/status-board.git`
2. `cd status-board/`
3. `npm install`
4. `npm start`

Is this correct way to run status board?

**Comment by jameswlane** [comment]
@dtsuran,
`status-board` is a library, so it cannot be run directly. You can do one of two things:
* You can clone the `status-board-example` repo [here](https://github.com/jameswlane/status-board-example) and run it.
* Use the CLI tool to create a new project. See [here](https://github.com/jameswlane/status-board-cli) 

If you have any more questions please let me know.
